#This script searches the reportArray array of dictionaries generated by the DPSTxtParser script
#field- Field to focus on
#value- Value to search for within field. Allows for regular expressions

Function searchReport{
    [CmdletBinding(DefaultParameterSetName='ByUserName')]
    param(
        [Parameter (
            mandatory=$True,
            valueFromPipeline=$True,
            valueFromPipelineByPropertyName=$True)]
         [System.Collections.ArrayList] $inputArray,
         [Parameter (
            mandatory=$True,
            valueFromPipeline=$True,
            valueFromPipelineByPropertyName=$True)]
         [string] $field,
         [Parameter (
            mandatory=$True,
            valueFromPipeline=$True,
            valueFromPipelineByPropertyName=$True)]
         [string] $value
    )

    #checks if a valid field is entered
    if($inputArray[0].keys -contains $field){
        #create a new searchedList to contain the matching reports
        [System.Collections.ArrayList] $searchedList= New-Object System.Collections.ArrayList
        #iterates through the array and adds matches into searchedList
        foreach ($case in $inputArray){
            if($case.$field -like "*$value*"){
                [void]$searchedList.add($case.clone())
            }
        }
    }
    else{
        Write-Error "Report does not contain such field"
    }
    return $searchedlist
}